# TCL File Generated by Component Editor 12.1sp1
# Fri Mar 24 16:16:09 MDT 2017
# DO NOT MODIFY


# 
# I2C_master "I2C_master" v1.0
# null 2017.03.24.16:16:09
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module I2C_master
# 
set_module_property NAME I2C_master
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME I2C_master
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL i2c_master
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file i2c_master.vhd VHDL PATH ../../i2c_master.vhd
add_fileset_file DE2_CONSTANTS.vhd VHDL PATH ../../ECE492_Projects/niosII_microc_lab2/DE2_CONSTANTS.vhd


# 
# parameters
# 
add_parameter input_clk INTEGER 50000000
set_parameter_property input_clk DEFAULT_VALUE 50000000
set_parameter_property input_clk DISPLAY_NAME input_clk
set_parameter_property input_clk TYPE INTEGER
set_parameter_property input_clk UNITS None
set_parameter_property input_clk HDL_PARAMETER true
add_parameter bus_clk INTEGER 400000
set_parameter_property bus_clk DEFAULT_VALUE 400000
set_parameter_property bus_clk DISPLAY_NAME bus_clk
set_parameter_property bus_clk TYPE INTEGER
set_parameter_property bus_clk UNITS None
set_parameter_property bus_clk HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset ""
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 addr writebyteenable_n Input 7
add_interface_port avalon_slave_0 rw beginbursttransfer_n Input 1
add_interface_port avalon_slave_0 data_wr writebyteenable_n Input 8
add_interface_port avalon_slave_0 busy readdatavalid_n Output 1
add_interface_port avalon_slave_0 data_rd readdata Output 8
add_interface_port avalon_slave_0 ack_error readdatavalid_n Output 1
add_interface_port avalon_slave_0 sda export Bidir 1
add_interface_port avalon_slave_0 scl export Bidir 1
add_interface_port avalon_slave_0 ena beginbursttransfer_n Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clock
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true

add_interface_port reset_n reset_n reset_n Input 1

